/**
 * All user-facing copy (Arabic). Architecture note: to add English later, create `en.ts` with the
 * same shape, pick the dictionary by locale in the root layout, and mirror `dir`/`lang`.
 */
export const ar = {
  brand: { name: "مجمع أميرة باشا", tagline: "الحلة – بابل", en: "AMEERA BASHA COMPLEX" },
  nav: {
    home: "الرئيسية",
    products: "المنتجات",
    categories: "الأقسام",
    delivery: "التوصيل",
    location: "موقعنا",
    about: "عن المجمع",
    contact: "تواصل معنا",
    social: "حسابات التواصل الاجتماعي",
    followUs: "تابعنا",
    opensNew: "يفتح في نافذة جديدة",
    menu: "القائمة",
    openMenu: "فتح القائمة",
    closeMenu: "إغلاق القائمة",
    main: "التنقل الرئيسي",
    skip: "تخطّي إلى المحتوى",
  },
  hero: {
    eyebrow: "الحلة – محافظة بابل",
    title: "كل ما تحتاجه العائلة... في مكان واحد",
    subtitle: "ملابس نسائية، ملابس أطفال، أزياء مدرسية وقرطاسية في مجمع أميرة باشا – الحلة",
    browse: "تصفح المنتجات",
    book: "احجز الآن",
    contact: "تواصل معنا",
    map: "موقعنا على الخريطة",
    mainLabel: "المنتجات الرئيسية",
    popular: "الأكثر بحثاً:",
    popularTerms: ["فساتين", "صدرية مدرسية", "حقائب", "بنات", "أولاد", "دفاتر"],
    searchLabel: "ابحث عن منتج",
    searchPlaceholder: "مثال: فستان، صدرية، حقيبة…",
    searchButton: "بحث",
    chips: ["التوصيل إلى جميع المحافظات العراقية", "حجز القطع عبر واتساب", "تواصل مباشر بالهاتف وواتساب"],
    caption: "من منتجات المجمع",
  },
  categories: {
    eyebrow: "الأقسام",
    title: "تسوّق حسب القسم",
    subtitle: "أقسام متعددة تناسب جميع أفراد العائلة.",
    explore: "استكشف",
    moreTitle: "أقسام أخرى في المجمع",
  },
  featured: {
    eyebrow: "منتجات مختارة",
    title: "من منتجات المجمع",
    subtitle: "مجموعة مختارة من منتجات نشرها المجمع. الأسعار والتوفر كما وردت في المنشور الأصلي، ويُرجى تأكيدها عند الحجز.",
    all: "عرض كل المنتجات",
  },
  why: {
    eyebrow: "عن المجمع",
    title: "لماذا مجمع أميرة باشا؟",
    items: [
      { icon: "grid", title: "تنوع المنتجات", text: "ملابس وحقائب وأحذية وإكسسوارات ومفروشات ومنتجات عناية في مكان واحد." },
      { icon: "users", title: "أقسام متعددة للعائلة", text: "ملابس نسائية وملابس بنات وأولاد ضمن المجمع نفسه." },
      { icon: "school", title: "ملابس مدرسية وقرطاسية", text: "صداري مدرسية ودفاتر وحقائب ومحافظ أقلام." },
      { icon: "booking", title: "إمكانية الحجز", text: "احجز القطعة التي تعجبك عبر واتساب أو بالاتصال بنا." },
      { icon: "truck", title: "التوصيل إلى المحافظات", text: "خدمة توصيل الطلبات إلى جميع المحافظات العراقية." },
      { icon: "chat", title: "تواصل مباشر", text: "اتصال وواتساب وفايبر وفيسبوك وتلغرام." },
    ],
    photoCaption: "من داخل المجمع",
    photoAlt: "صالة العرض الداخلية لمجمع أميرة باشا",
  },
  delivery: {
    eyebrow: "خدمة التوصيل",
    title: "التوصيل إلى جميع المحافظات العراقية",
    text: "نوفر خدمة حجز القطع وتوصيل الطلبات إلى جميع المحافظات العراقية.",
    steps: ["تصفّح المنتجات واختر القطعة", "احجزها أو استفسر عنها عبر واتساب", "أرسل اسمك ومحافظتك ومنطقتك لإتمام الطلب"],
    note: "للاستفسار عن تكلفة ومدة التوصيل تواصلوا معنا مباشرة.",
    cta: "اطلب الآن",
    browse: "تصفح المنتجات",
  },
  location: {
    eyebrow: "الموقع",
    title: "زورونا في الحلة",
    addressLabel: "العنوان",
    openMaps: "افتح الموقع على Google Maps",
    call: "اتصل بنا",
    mapTitle: "خريطة موقع مجمع أميرة باشا في الحلة",
    photoCaption: "واجهة المجمع",
    photoAlt: "واجهة مجمع أميرة باشا في شارع الجمعية بمدينة الحلة",
  },
  contact: {
    eyebrow: "التواصل",
    title: "تواصل معنا",
    subtitle: "للحجز والاستفسار عن المنتجات والتوصيل.",
    phone: "الهاتف",
    whatsapp: "واتساب",
    viber: "فايبر",
    facebook: "فيسبوك",
    telegram: "تلغرام",
    whatsappHint: "افتح محادثة",
    viberHint: "يتطلب تطبيق Viber",
    facebookHint: "صفحة المجمع",
    telegramHint: "قناة المجمع",
    phoneHint: "اتصال مباشر",
    maps: "Google Maps",
    mapsHint: "افتح موقع المجمع",
    copy: "نسخ الرقم",
    copied: "تم نسخ الرقم",
  },
  social: {
    eyebrow: "منصات التواصل",
    title: "تابعنا على منصات التواصل",
    subtitle: "تابع صور وفيديوهات المجمع وتواصل معنا على المنصة التي تفضّلها.",
    whatsappBlurb: "راسلونا للحجز والاستفسار",
    follow: (name: string) => `تابعنا على ${name}`,
  },
  footer: {
    about: "ملابس نسائية وأطفال، أزياء مدرسية، قرطاسية ومنتجات متنوعة في مدينة الحلة.",
    links: "روابط سريعة",
    follow: "تابعنا",
    disclaimer: "المنتجات والصور والأسعار مأخوذة من منشورات المجمع على قناته في Telegram وقد تتغير؛ يُرجى تأكيد السعر والتوفر عند الحجز.",
    copyright: "© Ameera Basha Complex",
  },
  products: {
    title: "المنتجات",
    subtitle: "تصفّح منتجات المجمع وابحث وفلتر حسب القسم والعمر والمقاس.",
    searchLabel: "ابحث في المنتجات",
    searchPlaceholder: "ابحث: فستان، حقيبة، صدرية…",
    category: "القسم",
    subcategory: "القسم الفرعي",
    age: "العمر",
    size: "المقاس",
    price: "السعر",
    sort: "ترتيب",
    all: "الكل",
    filters: "تصفية وترتيب",
    reset: "إزالة الفلاتر",
    clear: "مسح",
    clearSearch: "مسح البحث",
    filterByCategory: "تصفية حسب القسم",
    viewLabel: "طريقة العرض",
    gridView: "عرض شبكي",
    listView: "عرض قائمة",
    loadMore: "عرض المزيد",
    resultCount: (n: number) => (n === 0 ? "لا توجد منتجات" : n === 1 ? "منتج واحد" : n === 2 ? "منتجان" : n <= 10 ? `${n} منتجات` : `${n} منتجاً`),
    sortOptions: { newest: "الأحدث", "price-asc": "السعر: من الأقل", "price-desc": "السعر: من الأعلى" },
    ageHint: "يعرض المنتجات التي ذُكر عمرها في المنشور فقط.",
    priceHint: "يعرض المنتجات التي ذُكر سعرها فقط.",
    sizeHint: "يعرض المنتجات التي ذُكر مقاسها فقط.",
    noResultsTitle: "لم نجد منتجات مطابقة لبحثك",
    noResultsText: "جرّب تغيير كلمات البحث أو القسم.",
    tryInstead: "جرّب البحث عن:",
    errorTitle: "تعذّر تحميل المنتجات",
    errorText: "حدث خطأ غير متوقع. حاول مرة أخرى أو تواصل معنا مباشرة.",
    retry: "إعادة المحاولة",
    loading: "جاري تحميل المنتجات…",
    resultsHeading: "نتائج البحث",
  },
  product: {
    details: "عرض التفاصيل",
    reserve: "احجز القطعة",
    sourceLabel: "المصدر",
    share: "مشاركة المنتج",
    shareTitle: (name: string) => `${name} – مجمع أميرة باشا`,
    linkCopied: "تم نسخ رابط المنتج",
    copyLink: "نسخ الرابط",
    shareFailed: "تعذّرت المشاركة. انسخ الرابط يدوياً.",
    whatsapp: "استفسار عبر واتساب",
    call: "اتصال",
    priceOnRequest: "السعر عند الاستفسار",
    availableBySource: "متوفر حسب المنشور",
    availabilityUnknown: "التوفر عند الاستفسار",
    unavailable: "غير متوفر حالياً",
    unavailableNote: "هذه القطعة غير متوفرة حالياً. يمكنك الاستفسار عن موعد توفرها.",
    askAvailability: "استفسر عن التوفر",
    category: "القسم",
    size: "المقاس",
    age: "العمر",
    availability: "التوفر",
    posted: "تاريخ المنشور",
    priceNote: "السعر والتوفر كما ورد في المنشور الأصلي بتاريخ {date} وقد يتغير؛ نؤكده معك عند الحجز.",
    deliveryNote: "تتوفر خدمة التوصيل إلى جميع المحافظات العراقية.",
    source: (platform: string) => `المنشور الأصلي على ${platform}`,
    related: "منتجات مشابهة",
    gallery: "معرض صور المنتج",
    image: (n: number, total: number) => `صورة ${n} من ${total}`,
    notFoundTitle: "المنتج غير موجود",
    notFoundText: "قد يكون الرابط غير صحيح أو أن المنتج لم يعد معروضاً.",
    backToProducts: "العودة إلى المنتجات",
    breadcrumbs: "مسار التنقل",
  },
  reservation: {
    title: "حجز القطعة",
    intro: "املأ بياناتك لتسجيل الحجز لدى المجمع، ثم يمكنك إرسال التفاصيل عبر واتساب.",
    product: "المنتج",
    name: "الاسم",
    phone: "رقم الهاتف",
    governorate: "المحافظة",
    governoratePlaceholder: "اختر المحافظة",
    district: "المنطقة / الحي",
    address: "العنوان التفصيلي",
    addressPlaceholder: "أقرب نقطة دالة، رقم الدار…",
    size: "المقاس",
    sizePlaceholder: "اختر المقاس (اختياري)",
    sizeFree: "أو اكتب المقاس",
    quantity: "الكمية",
    notes: "ملاحظات",
    notesPlaceholder: "أي تفاصيل إضافية (اللون، الموديل…)",
    optional: "(اختياري)",
    submit: "تسجيل الحجز",
    sending: "جاري الحفظ…",
    cancel: "إلغاء",
    close: "إغلاق",
    errorSummary: "يرجى تصحيح الحقول التالية:",
    successTitle: "تم تسجيل طلب الحجز",
    numberLabel: "رقم الحجز",
    successText: "سجّلنا حجزك وسنتواصل معك لتأكيده. يمكنك أيضاً إرسال التفاصيل إلى المجمع عبر واتساب (لن يُرسل شيء إلا إذا ضغطت «إرسال» داخل واتساب).",
    sendWhatsapp: "إرسال التفاصيل عبر واتساب",
    errorTitle: "تعذّر تسجيل الحجز",
    errorText: "حدثت مشكلة أثناء حفظ الحجز. حاول مرة أخرى بعد قليل.",
    notSavedNote: "لم يُحفظ حجزك بعد. يمكنك إعادة المحاولة، أو التواصل مع المجمع مباشرة عبر واتساب.",
    backToForm: "العودة إلى النموذج",
    openWhatsapp: "التواصل عبر واتساب",
    copyRequest: "نسخ نص الطلب",
    copied: "تم نسخ نص الطلب",
  },
  states: {
    notFoundTitle: "الصفحة غير موجودة",
    notFoundText: "الرابط الذي فتحته غير صحيح أو تم نقل الصفحة.",
    errorTitle: "حدث خطأ غير متوقع",
    errorText: "نعتذر عن ذلك. حاول تحديث الصفحة أو تواصل معنا مباشرة.",
    home: "العودة للرئيسية",
    retry: "إعادة المحاولة",
  },
  mobileBar: { whatsapp: "واتساب", call: "اتصال", map: "الموقع", reserve: "احجز القطعة", label: "أزرار التواصل السريع" },
} as const;

export type Dictionary = typeof ar;
